export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
export const CATEGORY_RESPONSE = 'CATEGORY_RESPONSE';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

export const CATEGORY_ADD_REQUEST = 'CATEGORY_ADD_REQUEST';
export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS';
export const CATEGORY_ADD_ERROR = 'CATEGORY_ADD_ERROR';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_ERROR = 'CATEGORY_DELETE_ERROR';

export const CATEGORY_EDIT_REQUEST = 'CATEGORY_EDIT_REQUEST';
export const CATEGORY_EDIT_SUCCESS = 'CATEGORY_EDIT_SUCCESS';
export const CATEGORY_EDIT_ERROR = 'CATEGORY_EDIT_ERROR';

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_ERROR = 'CATEGORY_UPDATE_ERROR';

export const CATEGORY_DROPDOWN_REQUEST = 'CATEGORY_DROPDOWN_REQUEST';
export const CATEGORY_DROPDOWN_SUCCESS = 'CATEGORY_DROPDOWN_SUCCESS';
export const CATEGORY_DROPDOWN_ERROR = 'CATEGORY_DROPDOWN_ERROR';

export const CATEGORY_PRO_DROPDOWN_REQUEST = 'CATEGORY_PRO_DROPDOWN_REQUEST';
export const CATEGORY_PRO_DROPDOWN_SUCCESS = 'CATEGORY_PRO_DROPDOWN_SUCCESS';
export const CATEGORY_PRO_DROPDOWN_ERROR = 'CATEGORY_PRO_DROPDOWN_ERROR';

export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADD_ERROR = 'PRODUCT_ADD_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CLEAR_ALL = 'CLEAR_ALL';
