export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const BUSDETAILS_REQUEST = "BUSDETAILS_REQUEST";
export const BUSDETAILS_SUCCESS = "BUSDETAILS_SUCCESS";
export const BUSDETAILS_ERROR = "BUSDETAILS_ERROR";

export const BUS_DELETE_REQUEST = "BUS_DELETE_REQUEST";
export const BUS_DELETE_SUCCESS = "BUS_DELETE_SUCCESS";
export const BUS_DELETE_ERROR = "BUS_DELETE_ERROR";

export const BUS_GETBYID_REQUEST = "BUS_GETBYID_REQUEST";
export const BUS_GETBYID_SUCCESS = "BUS_GETBYID_SUCCESS";
export const BUS_GETBYID_ERROR = "BUS_GETBYID_ERROR";

export const ADD_NEW_BUS_REQUEST = "ADD_NEW_BUS_REQUEST";
export const ADD_NEW_BUS_SUCCESS = "ADD_NEW_BUS_SUCCESS";
export const ADD_NEW_BUS_ERROR = "ADD_NEW_BUS_ERROR";

export const ROUTE_DETAILS_REQUEST = "ROUTE_DETAILS_REQUEST";
export const ROUTE_DETAILS_SUCCESS = "ROUTE_DETAILS_SUCCESS";
export const ROUTE_DETAILS_ERROR = "ROUTE_DETAILS_ERROR";
